import './globals.css'
import AuthContext from "@/components/AuthContext";
import AuthStatus from "@/components/AuthStatus";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <AuthStatus/>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
